unit HlpRIPEMD160;

{$I ..\Include\HashLib.inc}

interface

uses
  HlpMDBase,
  HlpBits,
  HlpConverters,
  HlpIHash,
  HlpIHashInfo;

type
  TRIPEMD160 = class sealed(TMDBase, ITransformBlock)

  strict protected
    procedure TransformBlock(AData: PByte; ADataLength: Int32;
      AIndex: Int32); override;

  public
    constructor Create();
    procedure Initialize(); override;
    function Clone(): IHash; override;

  end;

implementation

{ TRIPEMD160 }

function TRIPEMD160.Clone(): IHash;
var
  LHashInstance: TRIPEMD160;
begin
  LHashInstance := TRIPEMD160.Create();
  LHashInstance.FState := System.Copy(FState);
  LHashInstance.FBuffer := FBuffer.Clone();
  LHashInstance.FProcessedBytesCount := FProcessedBytesCount;
  Result := LHashInstance;
  Result.BufferSize := BufferSize;
end;

constructor TRIPEMD160.Create;
begin
  inherited Create(5, 20);
end;

procedure TRIPEMD160.Initialize;
begin
  FState[4] := $C3D2E1F0;
  inherited Initialize();
end;

procedure TRIPEMD160.TransformBlock(AData: PByte; ADataLength: Int32;
  AIndex: Int32);
var
  LRegA, LRegB, LRegC, LRegD, LRegE, LRegAa, LRegBb, LRegCc, LRegDd, LRegEe: UInt32;
  LData: array [0 .. 15] of UInt32;
begin
  TConverters.le32_copy(AData, AIndex, @(LData[0]), 0, ADataLength);

  LRegA := FState[0];
  LRegB := FState[1];
  LRegC := FState[2];
  LRegD := FState[3];
  LRegE := FState[4];
  LRegAa := LRegA;
  LRegBb := LRegB;
  LRegCc := LRegC;
  LRegDd := LRegD;
  LRegEe := LRegE;

  LRegA := LRegA + (LData[0] + (LRegB xor LRegC xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 11) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[1] + (LRegA xor LRegB xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 14) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[2] + (LRegE xor LRegA xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 15) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[3] + (LRegD xor LRegE xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 12) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[4] + (LRegC xor LRegD xor LRegE));
  LRegB := TBits.RotateLeft32(LRegB, 5) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[5] + (LRegB xor LRegC xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 8) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[6] + (LRegA xor LRegB xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 7) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[7] + (LRegE xor LRegA xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 9) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[8] + (LRegD xor LRegE xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 11) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[9] + (LRegC xor LRegD xor LRegE));
  LRegB := TBits.RotateLeft32(LRegB, 13) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[10] + (LRegB xor LRegC xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 14) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[11] + (LRegA xor LRegB xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 15) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[12] + (LRegE xor LRegA xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 6) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[13] + (LRegD xor LRegE xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 7) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[14] + (LRegC xor LRegD xor LRegE));
  LRegB := TBits.RotateLeft32(LRegB, 9) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[15] + (LRegB xor LRegC xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 8) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);

  LRegAa := LRegAa + (LData[5] + C1 + (LRegBb xor (LRegCc or not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 8) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[14] + C1 + (LRegAa xor (LRegBb or not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 9) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[7] + C1 + (LRegEe xor (LRegAa or not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 9) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[0] + C1 + (LRegDd xor (LRegEe or not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 11) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[9] + C1 + (LRegCc xor (LRegDd or not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 13) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[2] + C1 + (LRegBb xor (LRegCc or not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 15) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[11] + C1 + (LRegAa xor (LRegBb or not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 15) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[4] + C1 + (LRegEe xor (LRegAa or not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 5) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[13] + C1 + (LRegDd xor (LRegEe or not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 7) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[6] + C1 + (LRegCc xor (LRegDd or not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 7) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[15] + C1 + (LRegBb xor (LRegCc or not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 8) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[8] + C1 + (LRegAa xor (LRegBb or not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 11) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[1] + C1 + (LRegEe xor (LRegAa or not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 14) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[10] + C1 + (LRegDd xor (LRegEe or not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 14) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[3] + C1 + (LRegCc xor (LRegDd or not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 12) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[12] + C1 + (LRegBb xor (LRegCc or not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 6) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);

  LRegE := LRegE + (LData[7] + C2 + ((LRegA and LRegB) or (not LRegA and LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 7) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[4] + C2 + ((LRegE and LRegA) or (not LRegE and LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 6) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[13] + C2 + ((LRegD and LRegE) or (not LRegD and LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 8) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[1] + C2 + ((LRegC and LRegD) or (not LRegC and LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 13) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[10] + C2 + ((LRegB and LRegC) or (not LRegB and LRegD)));
  LRegA := TBits.RotateLeft32(LRegA, 11) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[6] + C2 + ((LRegA and LRegB) or (not LRegA and LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 9) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[15] + C2 + ((LRegE and LRegA) or (not LRegE and LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 7) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[3] + C2 + ((LRegD and LRegE) or (not LRegD and LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 15) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[12] + C2 + ((LRegC and LRegD) or (not LRegC and LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 7) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[0] + C2 + ((LRegB and LRegC) or (not LRegB and LRegD)));
  LRegA := TBits.RotateLeft32(LRegA, 12) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[9] + C2 + ((LRegA and LRegB) or (not LRegA and LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 15) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[5] + C2 + ((LRegE and LRegA) or (not LRegE and LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 9) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[2] + C2 + ((LRegD and LRegE) or (not LRegD and LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 11) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[14] + C2 + ((LRegC and LRegD) or (not LRegC and LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 7) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[11] + C2 + ((LRegB and LRegC) or (not LRegB and LRegD)));
  LRegA := TBits.RotateLeft32(LRegA, 13) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[8] + C2 + ((LRegA and LRegB) or (not LRegA and LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 12) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);

  LRegEe := LRegEe + (LData[6] + C3 + ((LRegAa and LRegCc) or (LRegBb and not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 9) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[11] + C3 + ((LRegEe and LRegBb) or (LRegAa and not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 13) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[3] + C3 + ((LRegDd and LRegAa) or (LRegEe and not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 15) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[7] + C3 + ((LRegCc and LRegEe) or (LRegDd and not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 7) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[0] + C3 + ((LRegBb and LRegDd) or (LRegCc and not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 12) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[13] + C3 + ((LRegAa and LRegCc) or (LRegBb and not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 8) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[5] + C3 + ((LRegEe and LRegBb) or (LRegAa and not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 9) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[10] + C3 + ((LRegDd and LRegAa) or (LRegEe and not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 11) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[14] + C3 + ((LRegCc and LRegEe) or (LRegDd and not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 7) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[15] + C3 + ((LRegBb and LRegDd) or (LRegCc and not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 7) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[8] + C3 + ((LRegAa and LRegCc) or (LRegBb and not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 12) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[12] + C3 + ((LRegEe and LRegBb) or (LRegAa and not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 7) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[4] + C3 + ((LRegDd and LRegAa) or (LRegEe and not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 6) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[9] + C3 + ((LRegCc and LRegEe) or (LRegDd and not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 15) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[1] + C3 + ((LRegBb and LRegDd) or (LRegCc and not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 13) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[2] + C3 + ((LRegAa and LRegCc) or (LRegBb and not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 11) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);

  LRegD := LRegD + (LData[3] + C4 + ((LRegE or not LRegA) xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 11) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[10] + C4 + ((LRegD or not LRegE) xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 13) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[14] + C4 + ((LRegC or not LRegD) xor LRegE));
  LRegB := TBits.RotateLeft32(LRegB, 6) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[4] + C4 + ((LRegB or not LRegC) xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 7) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[9] + C4 + ((LRegA or not LRegB) xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 14) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[15] + C4 + ((LRegE or not LRegA) xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 9) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[8] + C4 + ((LRegD or not LRegE) xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 13) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[1] + C4 + ((LRegC or not LRegD) xor LRegE));
  LRegB := TBits.RotateLeft32(LRegB, 15) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[2] + C4 + ((LRegB or not LRegC) xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 14) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[7] + C4 + ((LRegA or not LRegB) xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 8) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[0] + C4 + ((LRegE or not LRegA) xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 13) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[6] + C4 + ((LRegD or not LRegE) xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 6) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[13] + C4 + ((LRegC or not LRegD) xor LRegE));
  LRegB := TBits.RotateLeft32(LRegB, 5) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[11] + C4 + ((LRegB or not LRegC) xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 12) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[5] + C4 + ((LRegA or not LRegB) xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 7) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[12] + C4 + ((LRegE or not LRegA) xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 5) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);

  LRegDd := LRegDd + (LData[15] + C5 + ((LRegEe or not LRegAa) xor LRegBb));
  LRegDd := TBits.RotateLeft32(LRegDd, 9) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[5] + C5 + ((LRegDd or not LRegEe) xor LRegAa));
  LRegCc := TBits.RotateLeft32(LRegCc, 7) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[1] + C5 + ((LRegCc or not LRegDd) xor LRegEe));
  LRegBb := TBits.RotateLeft32(LRegBb, 15) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[3] + C5 + ((LRegBb or not LRegCc) xor LRegDd));
  LRegAa := TBits.RotateLeft32(LRegAa, 11) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[7] + C5 + ((LRegAa or not LRegBb) xor LRegCc));
  LRegEe := TBits.RotateLeft32(LRegEe, 8) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[14] + C5 + ((LRegEe or not LRegAa) xor LRegBb));
  LRegDd := TBits.RotateLeft32(LRegDd, 6) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[6] + C5 + ((LRegDd or not LRegEe) xor LRegAa));
  LRegCc := TBits.RotateLeft32(LRegCc, 6) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[9] + C5 + ((LRegCc or not LRegDd) xor LRegEe));
  LRegBb := TBits.RotateLeft32(LRegBb, 14) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[11] + C5 + ((LRegBb or not LRegCc) xor LRegDd));
  LRegAa := TBits.RotateLeft32(LRegAa, 12) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[8] + C5 + ((LRegAa or not LRegBb) xor LRegCc));
  LRegEe := TBits.RotateLeft32(LRegEe, 13) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[12] + C5 + ((LRegEe or not LRegAa) xor LRegBb));
  LRegDd := TBits.RotateLeft32(LRegDd, 5) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[2] + C5 + ((LRegDd or not LRegEe) xor LRegAa));
  LRegCc := TBits.RotateLeft32(LRegCc, 14) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[10] + C5 + ((LRegCc or not LRegDd) xor LRegEe));
  LRegBb := TBits.RotateLeft32(LRegBb, 13) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[0] + C5 + ((LRegBb or not LRegCc) xor LRegDd));
  LRegAa := TBits.RotateLeft32(LRegAa, 13) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[4] + C5 + ((LRegAa or not LRegBb) xor LRegCc));
  LRegEe := TBits.RotateLeft32(LRegEe, 7) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[13] + C5 + ((LRegEe or not LRegAa) xor LRegBb));
  LRegDd := TBits.RotateLeft32(LRegDd, 5) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);

  LRegC := LRegC + (LData[1] + C6 + ((LRegD and LRegA) or (LRegE and not LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 11) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[9] + C6 + ((LRegC and LRegE) or (LRegD and not LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 12) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[11] + C6 + ((LRegB and LRegD) or (LRegC and not LRegD)));
  LRegA := TBits.RotateLeft32(LRegA, 14) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[10] + C6 + ((LRegA and LRegC) or (LRegB and not LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 15) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[0] + C6 + ((LRegE and LRegB) or (LRegA and not LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 14) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[8] + C6 + ((LRegD and LRegA) or (LRegE and not LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 15) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[12] + C6 + ((LRegC and LRegE) or (LRegD and not LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 9) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[4] + C6 + ((LRegB and LRegD) or (LRegC and not LRegD)));
  LRegA := TBits.RotateLeft32(LRegA, 8) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[13] + C6 + ((LRegA and LRegC) or (LRegB and not LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 9) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[3] + C6 + ((LRegE and LRegB) or (LRegA and not LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 14) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[7] + C6 + ((LRegD and LRegA) or (LRegE and not LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 5) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[15] + C6 + ((LRegC and LRegE) or (LRegD and not LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 6) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[14] + C6 + ((LRegB and LRegD) or (LRegC and not LRegD)));
  LRegA := TBits.RotateLeft32(LRegA, 8) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[5] + C6 + ((LRegA and LRegC) or (LRegB and not LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 6) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[6] + C6 + ((LRegE and LRegB) or (LRegA and not LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 5) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[2] + C6 + ((LRegD and LRegA) or (LRegE and not LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 12) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);

  LRegCc := LRegCc + (LData[8] + C7 + ((LRegDd and LRegEe) or (not LRegDd and LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 15) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[6] + C7 + ((LRegCc and LRegDd) or (not LRegCc and LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 5) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[4] + C7 + ((LRegBb and LRegCc) or (not LRegBb and LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 8) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[1] + C7 + ((LRegAa and LRegBb) or (not LRegAa and LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 11) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[3] + C7 + ((LRegEe and LRegAa) or (not LRegEe and LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 14) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[11] + C7 + ((LRegDd and LRegEe) or (not LRegDd and LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 14) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[15] + C7 + ((LRegCc and LRegDd) or (not LRegCc and LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 6) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[0] + C7 + ((LRegBb and LRegCc) or (not LRegBb and LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 14) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[5] + C7 + ((LRegAa and LRegBb) or (not LRegAa and LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 6) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[12] + C7 + ((LRegEe and LRegAa) or (not LRegEe and LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 9) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[2] + C7 + ((LRegDd and LRegEe) or (not LRegDd and LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 12) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[13] + C7 + ((LRegCc and LRegDd) or (not LRegCc and LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 9) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[9] + C7 + ((LRegBb and LRegCc) or (not LRegBb and LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 12) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[7] + C7 + ((LRegAa and LRegBb) or (not LRegAa and LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 5) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[10] + C7 + ((LRegEe and LRegAa) or (not LRegEe and LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 15) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[14] + C7 + ((LRegDd and LRegEe) or (not LRegDd and LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 8) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);

  LRegB := LRegB + (LData[4] + C8 + (LRegC xor (LRegD or not LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 9) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[0] + C8 + (LRegB xor (LRegC or not LRegD)));
  LRegA := TBits.RotateLeft32(LRegA, 15) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[5] + C8 + (LRegA xor (LRegB or not LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 5) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[9] + C8 + (LRegE xor (LRegA or not LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 11) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[7] + C8 + (LRegD xor (LRegE or not LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 6) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[12] + C8 + (LRegC xor (LRegD or not LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 8) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[2] + C8 + (LRegB xor (LRegC or not LRegD)));
  LRegA := TBits.RotateLeft32(LRegA, 13) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[10] + C8 + (LRegA xor (LRegB or not LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 12) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[14] + C8 + (LRegE xor (LRegA or not LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 5) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[1] + C8 + (LRegD xor (LRegE or not LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 12) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[3] + C8 + (LRegC xor (LRegD or not LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 13) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[8] + C8 + (LRegB xor (LRegC or not LRegD)));
  LRegA := TBits.RotateLeft32(LRegA, 14) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[11] + C8 + (LRegA xor (LRegB or not LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 11) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[6] + C8 + (LRegE xor (LRegA or not LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 8) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[15] + C8 + (LRegD xor (LRegE or not LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 5) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[13] + C8 + (LRegC xor (LRegD or not LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 6) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);

  LRegBb := LRegBb + (LData[12] + (LRegCc xor LRegDd xor LRegEe));
  LRegBb := TBits.RotateLeft32(LRegBb, 8) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[15] + (LRegBb xor LRegCc xor LRegDd));
  LRegAa := TBits.RotateLeft32(LRegAa, 5) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[10] + (LRegAa xor LRegBb xor LRegCc));
  LRegEe := TBits.RotateLeft32(LRegEe, 12) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[4] + (LRegEe xor LRegAa xor LRegBb));
  LRegDd := TBits.RotateLeft32(LRegDd, 9) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[1] + (LRegDd xor LRegEe xor LRegAa));
  LRegCc := TBits.RotateLeft32(LRegCc, 12) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[5] + (LRegCc xor LRegDd xor LRegEe));
  LRegBb := TBits.RotateLeft32(LRegBb, 5) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[8] + (LRegBb xor LRegCc xor LRegDd));
  LRegAa := TBits.RotateLeft32(LRegAa, 14) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[7] + (LRegAa xor LRegBb xor LRegCc));
  LRegEe := TBits.RotateLeft32(LRegEe, 6) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[6] + (LRegEe xor LRegAa xor LRegBb));
  LRegDd := TBits.RotateLeft32(LRegDd, 8) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[2] + (LRegDd xor LRegEe xor LRegAa));
  LRegCc := TBits.RotateLeft32(LRegCc, 13) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[13] + (LRegCc xor LRegDd xor LRegEe));
  LRegBb := TBits.RotateLeft32(LRegBb, 6) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[14] + (LRegBb xor LRegCc xor LRegDd));
  LRegAa := TBits.RotateLeft32(LRegAa, 5) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[0] + (LRegAa xor LRegBb xor LRegCc));
  LRegEe := TBits.RotateLeft32(LRegEe, 15) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[3] + (LRegEe xor LRegAa xor LRegBb));
  LRegDd := TBits.RotateLeft32(LRegDd, 13) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[9] + (LRegDd xor LRegEe xor LRegAa));
  LRegCc := TBits.RotateLeft32(LRegCc, 11) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[11] + (LRegCc xor LRegDd xor LRegEe));
  LRegBb := TBits.RotateLeft32(LRegBb, 11) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);

  LRegDd := LRegDd + LRegC + FState[1];
  FState[1] := FState[2] + LRegD + LRegEe;
  FState[2] := FState[3] + LRegE + LRegAa;
  FState[3] := FState[4] + LRegA + LRegBb;
  FState[4] := FState[0] + LRegB + LRegCc;
  FState[0] := LRegDd;

  System.FillChar(LData, System.SizeOf(LData), UInt32(0));
end;

end.
