unit HlpRIPEMD320;

{$I ..\Include\HashLib.inc}

interface

uses
  HlpMDBase,
  HlpBits,
  HlpConverters,
  HlpIHash,
  HlpIHashInfo;

type
  TRIPEMD320 = class sealed(TMDBase, ITransformBlock)

  strict protected
    procedure TransformBlock(AData: PByte; ADataLength: Int32;
      AIndex: Int32); override;

  public
    constructor Create();
    procedure Initialize(); override;
    function Clone(): IHash; override;

  end;

implementation

{ TRIPEMD320 }

function TRIPEMD320.Clone(): IHash;
var
  LHashInstance: TRIPEMD320;
begin
  LHashInstance := TRIPEMD320.Create();
  LHashInstance.FState := System.Copy(FState);
  LHashInstance.FBuffer := FBuffer.Clone();
  LHashInstance.FProcessedBytesCount := FProcessedBytesCount;
  Result := LHashInstance;
  Result.BufferSize := BufferSize;
end;

constructor TRIPEMD320.Create;
begin
  inherited Create(10, 40);
end;

procedure TRIPEMD320.Initialize;
begin
  FState[4] := $C3D2E1F0;
  FState[5] := $76543210;
  FState[6] := $FEDCBA98;
  FState[7] := $89ABCDEF;
  FState[8] := $01234567;
  FState[9] := $3C2D1E0F;

  inherited Initialize();

end;

procedure TRIPEMD320.TransformBlock(AData: PByte; ADataLength: Int32;
  AIndex: Int32);
var
  LRegA, LRegB, LRegC, LRegD, LRegE, LRegAa, LRegBb, LRegCc, LRegDd, LRegEe: UInt32;
  LData: array [0 .. 15] of UInt32;
begin
  TConverters.le32_copy(AData, AIndex, @(LData[0]), 0, ADataLength);

  LRegA := FState[0];
  LRegB := FState[1];
  LRegC := FState[2];
  LRegD := FState[3];
  LRegE := FState[4];
  LRegAa := FState[5];
  LRegBb := FState[6];
  LRegCc := FState[7];
  LRegDd := FState[8];
  LRegEe := FState[9];

  LRegA := LRegA + (LData[0] + (LRegB xor LRegC xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 11) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[1] + (LRegA xor LRegB xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 14) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[2] + (LRegE xor LRegA xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 15) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[3] + (LRegD xor LRegE xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 12) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[4] + (LRegC xor LRegD xor LRegE));
  LRegB := TBits.RotateLeft32(LRegB, 5) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[5] + (LRegB xor LRegC xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 8) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[6] + (LRegA xor LRegB xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 7) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[7] + (LRegE xor LRegA xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 9) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[8] + (LRegD xor LRegE xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 11) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[9] + (LRegC xor LRegD xor LRegE));
  LRegB := TBits.RotateLeft32(LRegB, 13) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[10] + (LRegB xor LRegC xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 14) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[11] + (LRegA xor LRegB xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 15) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[12] + (LRegE xor LRegA xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 6) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[13] + (LRegD xor LRegE xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 7) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[14] + (LRegC xor LRegD xor LRegE));
  LRegB := TBits.RotateLeft32(LRegB, 9) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[15] + (LRegB xor LRegC xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 8) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);

  LRegAa := LRegAa + (LData[5] + C1 + (LRegBb xor (LRegCc or not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 8) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[14] + C1 + (LRegAa xor (LRegBb or not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 9) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[7] + C1 + (LRegEe xor (LRegAa or not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 9) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[0] + C1 + (LRegDd xor (LRegEe or not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 11) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[9] + C1 + (LRegCc xor (LRegDd or not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 13) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[2] + C1 + (LRegBb xor (LRegCc or not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 15) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[11] + C1 + (LRegAa xor (LRegBb or not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 15) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[4] + C1 + (LRegEe xor (LRegAa or not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 5) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[13] + C1 + (LRegDd xor (LRegEe or not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 7) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[6] + C1 + (LRegCc xor (LRegDd or not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 7) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[15] + C1 + (LRegBb xor (LRegCc or not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 8) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[8] + C1 + (LRegAa xor (LRegBb or not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 11) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[1] + C1 + (LRegEe xor (LRegAa or not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 14) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[10] + C1 + (LRegDd xor (LRegEe or not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 14) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[3] + C1 + (LRegCc xor (LRegDd or not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 12) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[12] + C1 + (LRegBb xor (LRegCc or not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 6) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);

  LRegE := LRegE + (LData[7] + C2 + ((LRegAa and LRegB) or (not LRegAa and LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 7) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[4] + C2 + ((LRegE and LRegAa) or (not LRegE and LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 6) + LRegC;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegC := LRegC + (LData[13] + C2 + ((LRegD and LRegE) or (not LRegD and LRegAa)));
  LRegC := TBits.RotateLeft32(LRegC, 8) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[1] + C2 + ((LRegC and LRegD) or (not LRegC and LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 13) + LRegAa;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegAa := LRegAa + (LData[10] + C2 + ((LRegB and LRegC) or (not LRegB and LRegD)));
  LRegAa := TBits.RotateLeft32(LRegAa, 11) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[6] + C2 + ((LRegAa and LRegB) or (not LRegAa and LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 9) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[15] + C2 + ((LRegE and LRegAa) or (not LRegE and LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 7) + LRegC;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegC := LRegC + (LData[3] + C2 + ((LRegD and LRegE) or (not LRegD and LRegAa)));
  LRegC := TBits.RotateLeft32(LRegC, 15) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[12] + C2 + ((LRegC and LRegD) or (not LRegC and LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 7) + LRegAa;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegAa := LRegAa + (LData[0] + C2 + ((LRegB and LRegC) or (not LRegB and LRegD)));
  LRegAa := TBits.RotateLeft32(LRegAa, 12) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[9] + C2 + ((LRegAa and LRegB) or (not LRegAa and LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 15) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[5] + C2 + ((LRegE and LRegAa) or (not LRegE and LRegB)));
  LRegD := TBits.RotateLeft32(LRegD, 9) + LRegC;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegC := LRegC + (LData[2] + C2 + ((LRegD and LRegE) or (not LRegD and LRegAa)));
  LRegC := TBits.RotateLeft32(LRegC, 11) + LRegB;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegB := LRegB + (LData[14] + C2 + ((LRegC and LRegD) or (not LRegC and LRegE)));
  LRegB := TBits.RotateLeft32(LRegB, 7) + LRegAa;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegAa := LRegAa + (LData[11] + C2 + ((LRegB and LRegC) or (not LRegB and LRegD)));
  LRegAa := TBits.RotateLeft32(LRegAa, 13) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[8] + C2 + ((LRegAa and LRegB) or (not LRegAa and LRegC)));
  LRegE := TBits.RotateLeft32(LRegE, 12) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);

  LRegEe := LRegEe + (LData[6] + C3 + ((LRegA and LRegCc) or (LRegBb and not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 9) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[11] + C3 + ((LRegEe and LRegBb) or (LRegA and not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 13) + LRegCc;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegCc := LRegCc + (LData[3] + C3 + ((LRegDd and LRegA) or (LRegEe and not LRegA)));
  LRegCc := TBits.RotateLeft32(LRegCc, 15) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[7] + C3 + ((LRegCc and LRegEe) or (LRegDd and not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 7) + LRegA;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegA := LRegA + (LData[0] + C3 + ((LRegBb and LRegDd) or (LRegCc and not LRegDd)));
  LRegA := TBits.RotateLeft32(LRegA, 12) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[13] + C3 + ((LRegA and LRegCc) or (LRegBb and not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 8) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[5] + C3 + ((LRegEe and LRegBb) or (LRegA and not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 9) + LRegCc;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegCc := LRegCc + (LData[10] + C3 + ((LRegDd and LRegA) or (LRegEe and not LRegA)));
  LRegCc := TBits.RotateLeft32(LRegCc, 11) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[14] + C3 + ((LRegCc and LRegEe) or (LRegDd and not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 7) + LRegA;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegA := LRegA + (LData[15] + C3 + ((LRegBb and LRegDd) or (LRegCc and not LRegDd)));
  LRegA := TBits.RotateLeft32(LRegA, 7) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[8] + C3 + ((LRegA and LRegCc) or (LRegBb and not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 12) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[12] + C3 + ((LRegEe and LRegBb) or (LRegA and not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 7) + LRegCc;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegCc := LRegCc + (LData[4] + C3 + ((LRegDd and LRegA) or (LRegEe and not LRegA)));
  LRegCc := TBits.RotateLeft32(LRegCc, 6) + LRegBb;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegBb := LRegBb + (LData[9] + C3 + ((LRegCc and LRegEe) or (LRegDd and not LRegEe)));
  LRegBb := TBits.RotateLeft32(LRegBb, 15) + LRegA;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegA := LRegA + (LData[1] + C3 + ((LRegBb and LRegDd) or (LRegCc and not LRegDd)));
  LRegA := TBits.RotateLeft32(LRegA, 13) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[2] + C3 + ((LRegA and LRegCc) or (LRegBb and not LRegCc)));
  LRegEe := TBits.RotateLeft32(LRegEe, 11) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);

  LRegD := LRegD + (LData[3] + C4 + ((LRegE or not LRegAa) xor LRegBb));
  LRegD := TBits.RotateLeft32(LRegD, 11) + LRegC;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegC := LRegC + (LData[10] + C4 + ((LRegD or not LRegE) xor LRegAa));
  LRegC := TBits.RotateLeft32(LRegC, 13) + LRegBb;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegBb := LRegBb + (LData[14] + C4 + ((LRegC or not LRegD) xor LRegE));
  LRegBb := TBits.RotateLeft32(LRegBb, 6) + LRegAa;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegAa := LRegAa + (LData[4] + C4 + ((LRegBb or not LRegC) xor LRegD));
  LRegAa := TBits.RotateLeft32(LRegAa, 7) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[9] + C4 + ((LRegAa or not LRegBb) xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 14) + LRegD;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegD := LRegD + (LData[15] + C4 + ((LRegE or not LRegAa) xor LRegBb));
  LRegD := TBits.RotateLeft32(LRegD, 9) + LRegC;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegC := LRegC + (LData[8] + C4 + ((LRegD or not LRegE) xor LRegAa));
  LRegC := TBits.RotateLeft32(LRegC, 13) + LRegBb;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegBb := LRegBb + (LData[1] + C4 + ((LRegC or not LRegD) xor LRegE));
  LRegBb := TBits.RotateLeft32(LRegBb, 15) + LRegAa;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegAa := LRegAa + (LData[2] + C4 + ((LRegBb or not LRegC) xor LRegD));
  LRegAa := TBits.RotateLeft32(LRegAa, 14) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[7] + C4 + ((LRegAa or not LRegBb) xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 8) + LRegD;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegD := LRegD + (LData[0] + C4 + ((LRegE or not LRegAa) xor LRegBb));
  LRegD := TBits.RotateLeft32(LRegD, 13) + LRegC;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegC := LRegC + (LData[6] + C4 + ((LRegD or not LRegE) xor LRegAa));
  LRegC := TBits.RotateLeft32(LRegC, 6) + LRegBb;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegBb := LRegBb + (LData[13] + C4 + ((LRegC or not LRegD) xor LRegE));
  LRegBb := TBits.RotateLeft32(LRegBb, 5) + LRegAa;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegAa := LRegAa + (LData[11] + C4 + ((LRegBb or not LRegC) xor LRegD));
  LRegAa := TBits.RotateLeft32(LRegAa, 12) + LRegE;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegE := LRegE + (LData[5] + C4 + ((LRegAa or not LRegBb) xor LRegC));
  LRegE := TBits.RotateLeft32(LRegE, 7) + LRegD;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegD := LRegD + (LData[12] + C4 + ((LRegE or not LRegAa) xor LRegBb));
  LRegD := TBits.RotateLeft32(LRegD, 5) + LRegC;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);

  LRegDd := LRegDd + (LData[15] + C5 + ((LRegEe or not LRegA) xor LRegB));
  LRegDd := TBits.RotateLeft32(LRegDd, 9) + LRegCc;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegCc := LRegCc + (LData[5] + C5 + ((LRegDd or not LRegEe) xor LRegA));
  LRegCc := TBits.RotateLeft32(LRegCc, 7) + LRegB;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegB := LRegB + (LData[1] + C5 + ((LRegCc or not LRegDd) xor LRegEe));
  LRegB := TBits.RotateLeft32(LRegB, 15) + LRegA;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegA := LRegA + (LData[3] + C5 + ((LRegB or not LRegCc) xor LRegDd));
  LRegA := TBits.RotateLeft32(LRegA, 11) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[7] + C5 + ((LRegA or not LRegB) xor LRegCc));
  LRegEe := TBits.RotateLeft32(LRegEe, 8) + LRegDd;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegDd := LRegDd + (LData[14] + C5 + ((LRegEe or not LRegA) xor LRegB));
  LRegDd := TBits.RotateLeft32(LRegDd, 6) + LRegCc;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegCc := LRegCc + (LData[6] + C5 + ((LRegDd or not LRegEe) xor LRegA));
  LRegCc := TBits.RotateLeft32(LRegCc, 6) + LRegB;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegB := LRegB + (LData[9] + C5 + ((LRegCc or not LRegDd) xor LRegEe));
  LRegB := TBits.RotateLeft32(LRegB, 14) + LRegA;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegA := LRegA + (LData[11] + C5 + ((LRegB or not LRegCc) xor LRegDd));
  LRegA := TBits.RotateLeft32(LRegA, 12) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[8] + C5 + ((LRegA or not LRegB) xor LRegCc));
  LRegEe := TBits.RotateLeft32(LRegEe, 13) + LRegDd;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegDd := LRegDd + (LData[12] + C5 + ((LRegEe or not LRegA) xor LRegB));
  LRegDd := TBits.RotateLeft32(LRegDd, 5) + LRegCc;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegCc := LRegCc + (LData[2] + C5 + ((LRegDd or not LRegEe) xor LRegA));
  LRegCc := TBits.RotateLeft32(LRegCc, 14) + LRegB;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegB := LRegB + (LData[10] + C5 + ((LRegCc or not LRegDd) xor LRegEe));
  LRegB := TBits.RotateLeft32(LRegB, 13) + LRegA;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegA := LRegA + (LData[0] + C5 + ((LRegB or not LRegCc) xor LRegDd));
  LRegA := TBits.RotateLeft32(LRegA, 13) + LRegEe;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegEe := LRegEe + (LData[4] + C5 + ((LRegA or not LRegB) xor LRegCc));
  LRegEe := TBits.RotateLeft32(LRegEe, 7) + LRegDd;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegDd := LRegDd + (LData[13] + C5 + ((LRegEe or not LRegA) xor LRegB));
  LRegDd := TBits.RotateLeft32(LRegDd, 5) + LRegCc;
  LRegA := TBits.RotateLeft32(LRegA, 10);

  LRegCc := LRegCc + (LData[1] + C6 + ((LRegD and LRegAa) or (LRegE and not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 11) + LRegBb;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegBb := LRegBb + (LData[9] + C6 + ((LRegCc and LRegE) or (LRegD and not LRegE)));
  LRegBb := TBits.RotateLeft32(LRegBb, 12) + LRegAa;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegAa := LRegAa + (LData[11] + C6 + ((LRegBb and LRegD) or (LRegCc and not LRegD)));
  LRegAa := TBits.RotateLeft32(LRegAa, 14) + LRegE;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegE := LRegE + (LData[10] + C6 + ((LRegAa and LRegCc) or (LRegBb and not LRegCc)));
  LRegE := TBits.RotateLeft32(LRegE, 15) + LRegD;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegD := LRegD + (LData[0] + C6 + ((LRegE and LRegBb) or (LRegAa and not LRegBb)));
  LRegD := TBits.RotateLeft32(LRegD, 14) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[8] + C6 + ((LRegD and LRegAa) or (LRegE and not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 15) + LRegBb;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegBb := LRegBb + (LData[12] + C6 + ((LRegCc and LRegE) or (LRegD and not LRegE)));
  LRegBb := TBits.RotateLeft32(LRegBb, 9) + LRegAa;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegAa := LRegAa + (LData[4] + C6 + ((LRegBb and LRegD) or (LRegCc and not LRegD)));
  LRegAa := TBits.RotateLeft32(LRegAa, 8) + LRegE;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegE := LRegE + (LData[13] + C6 + ((LRegAa and LRegCc) or (LRegBb and not LRegCc)));
  LRegE := TBits.RotateLeft32(LRegE, 9) + LRegD;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegD := LRegD + (LData[3] + C6 + ((LRegE and LRegBb) or (LRegAa and not LRegBb)));
  LRegD := TBits.RotateLeft32(LRegD, 14) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[7] + C6 + ((LRegD and LRegAa) or (LRegE and not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 5) + LRegBb;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegBb := LRegBb + (LData[15] + C6 + ((LRegCc and LRegE) or (LRegD and not LRegE)));
  LRegBb := TBits.RotateLeft32(LRegBb, 6) + LRegAa;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegAa := LRegAa + (LData[14] + C6 + ((LRegBb and LRegD) or (LRegCc and not LRegD)));
  LRegAa := TBits.RotateLeft32(LRegAa, 8) + LRegE;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegE := LRegE + (LData[5] + C6 + ((LRegAa and LRegCc) or (LRegBb and not LRegCc)));
  LRegE := TBits.RotateLeft32(LRegE, 6) + LRegD;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegD := LRegD + (LData[6] + C6 + ((LRegE and LRegBb) or (LRegAa and not LRegBb)));
  LRegD := TBits.RotateLeft32(LRegD, 5) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[2] + C6 + ((LRegD and LRegAa) or (LRegE and not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 12) + LRegBb;
  LRegE := TBits.RotateLeft32(LRegE, 10);

  LRegC := LRegC + (LData[8] + C7 + ((LRegDd and LRegEe) or (not LRegDd and LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 15) + LRegB;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegB := LRegB + (LData[6] + C7 + ((LRegC and LRegDd) or (not LRegC and LRegEe)));
  LRegB := TBits.RotateLeft32(LRegB, 5) + LRegA;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegA := LRegA + (LData[4] + C7 + ((LRegB and LRegC) or (not LRegB and LRegDd)));
  LRegA := TBits.RotateLeft32(LRegA, 8) + LRegEe;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegEe := LRegEe + (LData[1] + C7 + ((LRegA and LRegB) or (not LRegA and LRegC)));
  LRegEe := TBits.RotateLeft32(LRegEe, 11) + LRegDd;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegDd := LRegDd + (LData[3] + C7 + ((LRegEe and LRegA) or (not LRegEe and LRegB)));
  LRegDd := TBits.RotateLeft32(LRegDd, 14) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[11] + C7 + ((LRegDd and LRegEe) or (not LRegDd and LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 14) + LRegB;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegB := LRegB + (LData[15] + C7 + ((LRegC and LRegDd) or (not LRegC and LRegEe)));
  LRegB := TBits.RotateLeft32(LRegB, 6) + LRegA;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegA := LRegA + (LData[0] + C7 + ((LRegB and LRegC) or (not LRegB and LRegDd)));
  LRegA := TBits.RotateLeft32(LRegA, 14) + LRegEe;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegEe := LRegEe + (LData[5] + C7 + ((LRegA and LRegB) or (not LRegA and LRegC)));
  LRegEe := TBits.RotateLeft32(LRegEe, 6) + LRegDd;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegDd := LRegDd + (LData[12] + C7 + ((LRegEe and LRegA) or (not LRegEe and LRegB)));
  LRegDd := TBits.RotateLeft32(LRegDd, 9) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[2] + C7 + ((LRegDd and LRegEe) or (not LRegDd and LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 12) + LRegB;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegB := LRegB + (LData[13] + C7 + ((LRegC and LRegDd) or (not LRegC and LRegEe)));
  LRegB := TBits.RotateLeft32(LRegB, 9) + LRegA;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegA := LRegA + (LData[9] + C7 + ((LRegB and LRegC) or (not LRegB and LRegDd)));
  LRegA := TBits.RotateLeft32(LRegA, 12) + LRegEe;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegEe := LRegEe + (LData[7] + C7 + ((LRegA and LRegB) or (not LRegA and LRegC)));
  LRegEe := TBits.RotateLeft32(LRegEe, 5) + LRegDd;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegDd := LRegDd + (LData[10] + C7 + ((LRegEe and LRegA) or (not LRegEe and LRegB)));
  LRegDd := TBits.RotateLeft32(LRegDd, 15) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[14] + C7 + ((LRegDd and LRegEe) or (not LRegDd and LRegA)));
  LRegC := TBits.RotateLeft32(LRegC, 8) + LRegB;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);

  LRegBb := LRegBb + (LData[4] + C8 + (LRegCc xor (LRegDd or not LRegE)));
  LRegBb := TBits.RotateLeft32(LRegBb, 9) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[0] + C8 + (LRegBb xor (LRegCc or not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 15) + LRegE;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegE := LRegE + (LData[5] + C8 + (LRegAa xor (LRegBb or not LRegCc)));
  LRegE := TBits.RotateLeft32(LRegE, 5) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[9] + C8 + (LRegE xor (LRegAa or not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 11) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[7] + C8 + (LRegDd xor (LRegE or not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 6) + LRegBb;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegBb := LRegBb + (LData[12] + C8 + (LRegCc xor (LRegDd or not LRegE)));
  LRegBb := TBits.RotateLeft32(LRegBb, 8) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[2] + C8 + (LRegBb xor (LRegCc or not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 13) + LRegE;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegE := LRegE + (LData[10] + C8 + (LRegAa xor (LRegBb or not LRegCc)));
  LRegE := TBits.RotateLeft32(LRegE, 12) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[14] + C8 + (LRegE xor (LRegAa or not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 5) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[1] + C8 + (LRegDd xor (LRegE or not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 12) + LRegBb;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegBb := LRegBb + (LData[3] + C8 + (LRegCc xor (LRegDd or not LRegE)));
  LRegBb := TBits.RotateLeft32(LRegBb, 13) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);
  LRegAa := LRegAa + (LData[8] + C8 + (LRegBb xor (LRegCc or not LRegDd)));
  LRegAa := TBits.RotateLeft32(LRegAa, 14) + LRegE;
  LRegCc := TBits.RotateLeft32(LRegCc, 10);
  LRegE := LRegE + (LData[11] + C8 + (LRegAa xor (LRegBb or not LRegCc)));
  LRegE := TBits.RotateLeft32(LRegE, 11) + LRegDd;
  LRegBb := TBits.RotateLeft32(LRegBb, 10);
  LRegDd := LRegDd + (LData[6] + C8 + (LRegE xor (LRegAa or not LRegBb)));
  LRegDd := TBits.RotateLeft32(LRegDd, 8) + LRegCc;
  LRegAa := TBits.RotateLeft32(LRegAa, 10);
  LRegCc := LRegCc + (LData[15] + C8 + (LRegDd xor (LRegE or not LRegAa)));
  LRegCc := TBits.RotateLeft32(LRegCc, 5) + LRegBb;
  LRegE := TBits.RotateLeft32(LRegE, 10);
  LRegBb := LRegBb + (LData[13] + C8 + (LRegCc xor (LRegDd or not LRegE)));
  LRegBb := TBits.RotateLeft32(LRegBb, 6) + LRegAa;
  LRegDd := TBits.RotateLeft32(LRegDd, 10);

  LRegB := LRegB + (LData[12] + (LRegC xor LRegD xor LRegEe));
  LRegB := TBits.RotateLeft32(LRegB, 8) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[15] + (LRegB xor LRegC xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 5) + LRegEe;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegEe := LRegEe + (LData[10] + (LRegA xor LRegB xor LRegC));
  LRegEe := TBits.RotateLeft32(LRegEe, 12) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[4] + (LRegEe xor LRegA xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 9) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[1] + (LRegD xor LRegEe xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 12) + LRegB;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegB := LRegB + (LData[5] + (LRegC xor LRegD xor LRegEe));
  LRegB := TBits.RotateLeft32(LRegB, 5) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[8] + (LRegB xor LRegC xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 14) + LRegEe;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegEe := LRegEe + (LData[7] + (LRegA xor LRegB xor LRegC));
  LRegEe := TBits.RotateLeft32(LRegEe, 6) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[6] + (LRegEe xor LRegA xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 8) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[2] + (LRegD xor LRegEe xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 13) + LRegB;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegB := LRegB + (LData[13] + (LRegC xor LRegD xor LRegEe));
  LRegB := TBits.RotateLeft32(LRegB, 6) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);
  LRegA := LRegA + (LData[14] + (LRegB xor LRegC xor LRegD));
  LRegA := TBits.RotateLeft32(LRegA, 5) + LRegEe;
  LRegC := TBits.RotateLeft32(LRegC, 10);
  LRegEe := LRegEe + (LData[0] + (LRegA xor LRegB xor LRegC));
  LRegEe := TBits.RotateLeft32(LRegEe, 15) + LRegD;
  LRegB := TBits.RotateLeft32(LRegB, 10);
  LRegD := LRegD + (LData[3] + (LRegEe xor LRegA xor LRegB));
  LRegD := TBits.RotateLeft32(LRegD, 13) + LRegC;
  LRegA := TBits.RotateLeft32(LRegA, 10);
  LRegC := LRegC + (LData[9] + (LRegD xor LRegEe xor LRegA));
  LRegC := TBits.RotateLeft32(LRegC, 11) + LRegB;
  LRegEe := TBits.RotateLeft32(LRegEe, 10);
  LRegB := LRegB + (LData[11] + (LRegC xor LRegD xor LRegEe));
  LRegB := TBits.RotateLeft32(LRegB, 11) + LRegA;
  LRegD := TBits.RotateLeft32(LRegD, 10);

  FState[0] := FState[0] + LRegAa;
  FState[1] := FState[1] + LRegBb;
  FState[2] := FState[2] + LRegCc;
  FState[3] := FState[3] + LRegDd;
  FState[4] := FState[4] + LRegEe;
  FState[5] := FState[5] + LRegA;
  FState[6] := FState[6] + LRegB;
  FState[7] := FState[7] + LRegC;
  FState[8] := FState[8] + LRegD;
  FState[9] := FState[9] + LRegE;

  System.FillChar(LData, System.SizeOf(LData), UInt32(0));
end;

end.
